2016/10/31 22:37:54 [error] [system.db.CDbCommand] Не удалось выполнить CDbCommand::execute(): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`advert`.`authassignment`, CONSTRAINT `authassignment_ibfk_1` FOREIGN KEY (`itemname`) REFERENCES `authitem` (`name`) ON DELETE CASCADE ON UPDATE CASCADE). Выполнявшийся SQL-запрос: INSERT INTO `AuthAssignment` (`itemname`, `userid`, `bizrule`, `data`) VALUES (:itemname, :userid, :bizrule, :data).
in C:\Apache2.2\htdocs\yii\advert\protected\controllers\UserController.php (77)
in C:\Apache2.2\htdocs\yii\advert\index.php (13)
2016/10/31 22:37:54 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand не удалось исполнить SQL-запрос: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`advert`.`authassignment`, CONSTRAINT `authassignment_ibfk_1` FOREIGN KEY (`itemname`) REFERENCES `authitem` (`name`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `AuthAssignment` (`itemname`, `userid`, `bizrule`, `data`) VALUES (:itemname, :userid, :bizrule, :data)' in C:\Apache2.2\htdocs\yii\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\Apache2.2\htdocs\yii\framework\db\CDbCommand.php(1278): CDbCommand->execute(Array)
#1 C:\Apache2.2\htdocs\yii\framework\web\auth\CDbAuthManager.php(263): CDbCommand->insert('AuthAssignment', Array)
#2 C:\Apache2.2\htdocs\yii\advert\protected\controllers\UserController.php(77): CDbAuthManager->assign('reader', '5')
#3 C:\Apache2.2\htdocs\yii\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#4 C:\Apache2.2\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\Apache2.2\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\Apache2.2\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\Apache2.2\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\Apache2.2\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#9 C:\Apache2.2\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/create')
#10 C:\Apache2.2\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 C:\Apache2.2\htdocs\yii\advert\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/yii/advert/user/create
HTTP_REFERER=http://localhost/yii/advert/user/create
---
2016/10/31 23:13:41 [error] [php] Trying to get property of non-object (C:\Apache2.2\htdocs\yii\advert\protected\views\user\update1.php:7)
Stack trace:
#0 C:\Apache2.2\htdocs\yii\framework\web\CController.php(869): UserController->renderFile()
#1 C:\Apache2.2\htdocs\yii\framework\web\CController.php(782): UserController->renderPartial()
#2 C:\Apache2.2\htdocs\yii\advert\protected\controllers\UserController.php(113): UserController->render()
#3 unknown(0): UserController->actionUpdate()
#4 C:\Apache2.2\htdocs\yii\framework\web\actions\CAction.php(109): ReflectionMethod->invokeArgs()
#5 C:\Apache2.2\htdocs\yii\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#6 C:\Apache2.2\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#7 C:\Apache2.2\htdocs\yii\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#8 C:\Apache2.2\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#9 C:\Apache2.2\htdocs\yii\framework\web\CController.php(265): UserController->runActionWithFilters()
#10 C:\Apache2.2\htdocs\yii\framework\web\CWebApplication.php(282): UserController->run()
#11 C:\Apache2.2\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\Apache2.2\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\Apache2.2\htdocs\yii\advert\index.php(13): CWebApplication->run()
REQUEST_URI=/yii/advert/user/update/6
in C:\Apache2.2\htdocs\yii\advert\protected\views\user\update1.php (7)
in C:\Apache2.2\htdocs\yii\advert\protected\controllers\UserController.php (113)
in C:\Apache2.2\htdocs\yii\advert\index.php (13)
2016/10/31 23:15:11 [error] [php] Trying to get property of non-object (C:\Apache2.2\htdocs\yii\advert\protected\views\user\update1.php:14)
Stack trace:
#0 C:\Apache2.2\htdocs\yii\framework\web\CController.php(869): UserController->renderFile()
#1 C:\Apache2.2\htdocs\yii\framework\web\CController.php(782): UserController->renderPartial()
#2 C:\Apache2.2\htdocs\yii\advert\protected\controllers\UserController.php(113): UserController->render()
#3 unknown(0): UserController->actionUpdate()
#4 C:\Apache2.2\htdocs\yii\framework\web\actions\CAction.php(109): ReflectionMethod->invokeArgs()
#5 C:\Apache2.2\htdocs\yii\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#6 C:\Apache2.2\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#7 C:\Apache2.2\htdocs\yii\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#8 C:\Apache2.2\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#9 C:\Apache2.2\htdocs\yii\framework\web\CController.php(265): UserController->runActionWithFilters()
#10 C:\Apache2.2\htdocs\yii\framework\web\CWebApplication.php(282): UserController->run()
#11 C:\Apache2.2\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\Apache2.2\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\Apache2.2\htdocs\yii\advert\index.php(13): CWebApplication->run()
REQUEST_URI=/yii/advert/user/update/6
in C:\Apache2.2\htdocs\yii\advert\protected\views\user\update1.php (14)
in C:\Apache2.2\htdocs\yii\advert\protected\controllers\UserController.php (113)
in C:\Apache2.2\htdocs\yii\advert\index.php (13)
2016/10/31 23:32:31 [error] [system.db.CDbCommand] Не удалось выполнить CDbCommand::execute(): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`advert`.`authassignment`, CONSTRAINT `authassignment_ibfk_1` FOREIGN KEY (`itemname`) REFERENCES `authitem` (`name`) ON DELETE CASCADE ON UPDATE CASCADE). Выполнявшийся SQL-запрос: INSERT INTO `AuthAssignment` (`itemname`, `userid`, `bizrule`, `data`) VALUES (:itemname, :userid, :bizrule, :data).
in C:\Apache2.2\htdocs\yii\advert\protected\controllers\UserController.php (77)
in C:\Apache2.2\htdocs\yii\advert\index.php (13)
2016/10/31 23:32:31 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand не удалось исполнить SQL-запрос: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`advert`.`authassignment`, CONSTRAINT `authassignment_ibfk_1` FOREIGN KEY (`itemname`) REFERENCES `authitem` (`name`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `AuthAssignment` (`itemname`, `userid`, `bizrule`, `data`) VALUES (:itemname, :userid, :bizrule, :data)' in C:\Apache2.2\htdocs\yii\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\Apache2.2\htdocs\yii\framework\db\CDbCommand.php(1278): CDbCommand->execute(Array)
#1 C:\Apache2.2\htdocs\yii\framework\web\auth\CDbAuthManager.php(263): CDbCommand->insert('AuthAssignment', Array)
#2 C:\Apache2.2\htdocs\yii\advert\protected\controllers\UserController.php(77): CDbAuthManager->assign('reader', '7')
#3 C:\Apache2.2\htdocs\yii\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#4 C:\Apache2.2\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\Apache2.2\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\Apache2.2\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\Apache2.2\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\Apache2.2\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#9 C:\Apache2.2\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/create')
#10 C:\Apache2.2\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 C:\Apache2.2\htdocs\yii\advert\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/yii/advert/user/create
HTTP_REFERER=http://localhost/yii/advert/user/create
---
2016/10/31 23:42:37 [error] [system.db.CDbCommand] Не удалось выполнить CDbCommand::execute(): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`advert`.`authassignment`, CONSTRAINT `authassignment_ibfk_1` FOREIGN KEY (`itemname`) REFERENCES `authitem` (`name`) ON DELETE CASCADE ON UPDATE CASCADE). Выполнявшийся SQL-запрос: INSERT INTO `AuthAssignment` (`itemname`, `userid`, `bizrule`, `data`) VALUES (:itemname, :userid, :bizrule, :data).
in C:\Apache2.2\htdocs\yii\advert\protected\controllers\UserController.php (77)
in C:\Apache2.2\htdocs\yii\advert\index.php (13)
2016/10/31 23:42:37 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand не удалось исполнить SQL-запрос: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`advert`.`authassignment`, CONSTRAINT `authassignment_ibfk_1` FOREIGN KEY (`itemname`) REFERENCES `authitem` (`name`) ON DELETE CASCADE ON UPDATE CASCADE). The SQL statement executed was: INSERT INTO `AuthAssignment` (`itemname`, `userid`, `bizrule`, `data`) VALUES (:itemname, :userid, :bizrule, :data)' in C:\Apache2.2\htdocs\yii\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\Apache2.2\htdocs\yii\framework\db\CDbCommand.php(1278): CDbCommand->execute(Array)
#1 C:\Apache2.2\htdocs\yii\framework\web\auth\CDbAuthManager.php(263): CDbCommand->insert('AuthAssignment', Array)
#2 C:\Apache2.2\htdocs\yii\advert\protected\controllers\UserController.php(77): CDbAuthManager->assign('reader', '8')
#3 C:\Apache2.2\htdocs\yii\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#4 C:\Apache2.2\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\Apache2.2\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\Apache2.2\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\Apache2.2\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\Apache2.2\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#9 C:\Apache2.2\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/create')
#10 C:\Apache2.2\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 C:\Apache2.2\htdocs\yii\advert\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/yii/advert/user/create
HTTP_REFERER=http://localhost/yii/advert/user/create
---
2016/11/01 18:42:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "site".' in C:\Apache2.2\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\Apache2.2\htdocs\yii\framework\web\CController.php(270): CController->missingAction('site')
#1 C:\Apache2.2\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('site')
#2 C:\Apache2.2\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/site/auth')
#3 C:\Apache2.2\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\Apache2.2\htdocs\yii\advert\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/advert/user/site/auth
---
2016/11/01 22:18:12 [error] [system.db.CDbCommand] Не удалось выполнить CDbCommand::execute(): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'create' for key 'PRIMARY'. Выполнявшийся SQL-запрос: INSERT INTO `AuthItem` (`name`, `type`, `description`, `bizrule`, `data`) VALUES (:name, :type, :description, :bizrule, :data).
in C:\Apache2.2\htdocs\yii\advert\protected\views\site\auth.php (4)
in C:\Apache2.2\htdocs\yii\advert\protected\controllers\SiteController.php (123)
in C:\Apache2.2\htdocs\yii\advert\index.php (13)
2016/11/01 22:18:12 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand не удалось исполнить SQL-запрос: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'create' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `AuthItem` (`name`, `type`, `description`, `bizrule`, `data`) VALUES (:name, :type, :description, :bizrule, :data)' in C:\Apache2.2\htdocs\yii\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\Apache2.2\htdocs\yii\framework\db\CDbCommand.php(1278): CDbCommand->execute(Array)
#1 C:\Apache2.2\htdocs\yii\framework\web\auth\CDbAuthManager.php(444): CDbCommand->insert('AuthItem', Array)
#2 C:\Apache2.2\htdocs\yii\framework\web\auth\CAuthManager.php(100): CDbAuthManager->createAuthItem('create', 0, 'create a post', NULL, NULL)
#3 C:\Apache2.2\htdocs\yii\advert\protected\views\site\auth.php(4): CAuthManager->createOperation('create', 'create a post')
#4 C:\Apache2.2\htdocs\yii\framework\web\CBaseController.php(126): require('C:\Apache2.2\ht...')
#5 C:\Apache2.2\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\Apache2.2\ht...', NULL, true)
#6 C:\Apache2.2\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\Apache2.2\ht...', NULL, true)
#7 C:\Apache2.2\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('auth', NULL, true)
#8 C:\Apache2.2\htdocs\yii\advert\protected\controllers\SiteController.php(123): CController->render('auth')
#9 C:\Apache2.2\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionAuth()
#10 C:\Apache2.2\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\Apache2.2\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\Apache2.2\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\Apache2.2\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('auth')
#14 C:\Apache2.2\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/auth')
#15 C:\Apache2.2\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 C:\Apache2.2\htdocs\yii\advert\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/yii/advert/site/auth
---
2016/11/01 22:28:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "auth".' in C:\Apache2.2\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\Apache2.2\htdocs\yii\framework\web\CController.php(270): CController->missingAction('auth')
#1 C:\Apache2.2\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('auth')
#2 C:\Apache2.2\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/auth')
#3 C:\Apache2.2\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\Apache2.2\htdocs\yii\advert\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/advert/site/auth
---
2016/11/01 23:04:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "auth".' in C:\Apache2.2\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\Apache2.2\htdocs\yii\framework\web\CController.php(270): CController->missingAction('auth')
#1 C:\Apache2.2\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('auth')
#2 C:\Apache2.2\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/auth')
#3 C:\Apache2.2\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\Apache2.2\htdocs\yii\advert\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/advert/site/auth
---
2016/11/01 23:45:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "auth".' in C:\Apache2.2\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\Apache2.2\htdocs\yii\framework\web\CController.php(270): CController->missingAction('auth')
#1 C:\Apache2.2\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('auth')
#2 C:\Apache2.2\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/auth')
#3 C:\Apache2.2\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\Apache2.2\htdocs\yii\advert\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/advert/site/auth
---
